DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_LOG;

CREATE TABLE EMPLOYEE (
  EMPLOYEEID INTEGER NOT NULL PRIMARY KEY,
  FIRSTNAME VARCHAR2(50) NOT NULL,
  LASTNAME VARCHAR2(50) NOT NULL,
  ADDR_LINE1 VARCHAR2(50) NOT NULL,
  ADDR_LINE2 VARCHAR2(50),
  CITY VARCHAR2(50),
  STATE VARCHAR2(50),
  ZIP VARCHAR2(50)
);

CREATE TABLE EMPLOYEE_LOG(

  USERNAME VARCHAR2(50) NOT NULL,
  DATESTAMP DATE NOT NULL,
  EMPLOYEEID INTEGER NOT NULL,
  ACTION CHAR NOT NULL,         -- 'I', 'U', 'D' (insert, update, delete)
  
  OLDFIRSTNAME VARCHAR2(50),
  OLDLASTNAME VARCHAR2(50),
  OLDADDR_LINE1 VARCHAR2(50),
  OLDADDR_LINE2 VARCHAR2(50),
  OLDCITY VARCHAR2(50),
  OLDSTATE VARCHAR2(50),
  OLDZIP VARCHAR2(50),
  
  NEWFIRSTNAME VARCHAR2(50),
  NEWLASTNAME VARCHAR2(50),
  NEWADDR_LINE1 VARCHAR2(50),
  NEWADDR_LINE2 VARCHAR2(50),
  NEWCITY VARCHAR2(50),
  NEWSTATE VARCHAR2(50),
  NEWZIP VARCHAR2(50),
  
  CONSTRAINT PK_EMPLOYEE_LOG PRIMARY KEY (USERNAME, DATESTAMP, EMPLOYEEID, ACTION)
);